[workspace]
members = [
    "crates/bdk",
    "example-crates/esplora-wallet",
    "example-crates/electrum-wallet",
    "example-crates/example-lib"
]

[workspace.package]
authors = ["Bitcoin Dev Kit Developers"]
