//! [`TxOutIndex`] is a unified script-pubkey indexer that tracks both descriptor-based keychains
//! (wildcard and non-wildcard) and raw script pubkeys behind a single API.
//!
//! It is intended as a replacement for the
//! [`KeychainTxOutIndex`](crate::keychain_txout::KeychainTxOutIndex) /
//! [`SpkTxOutIndex`] split: instead of forcing the caller to decide between "wildcard descriptor"
//! and "fixed script" at the type level, both kinds of tracking are dispatched internally on the
//! supplied keychain identifier `K`.

use crate::{
    alloc::boxed::Box,
    collections::*,
    indexer::keychain_txout,
    miniscript::{Descriptor, DescriptorPublicKey},
    spk_client::{FullScanRequestBuilder, SyncRequestBuilder},
    spk_iter::BIP32_MAX_INDEX,
    spk_txout::SpkTxOutIndex,
    DescriptorExt, DescriptorId, Indexed, Indexer, KeychainIndexed, SpkIterator,
};
use alloc::{borrow::ToOwned, vec::Vec};
use bitcoin::{
    key::Secp256k1, Amount, OutPoint, Script, ScriptBuf, SignedAmount, Transaction, TxOut, Txid,
};
use core::{
    fmt::Debug,
    ops::{Bound, RangeBounds},
};

use crate::spk_txout::{CreatedTxOut, SpentTxOut};

/// The default lookahead for a [`TxOutIndex`].
pub const DEFAULT_LOOKAHEAD: u32 = 25;

/// `ChangeSet` represents persistent updates to a [`TxOutIndex`].
///
/// Only descriptor-based state is recorded — raw script pubkeys registered through
/// [`TxOutIndex::insert_spk`] are re-registered by the caller after a reload, the same way
/// descriptors are.
///
/// This is a re-export of [`keychain_txout::ChangeSet`] so callers can mix changesets generated by
/// either indexer without conversion.
pub type ChangeSet = keychain_txout::ChangeSet;

/// A unified script-pubkey indexer.
///
/// `TxOutIndex<K>` tracks script pubkeys of interest under a single keychain identifier `K`.
/// A given keychain may be backed by:
///
/// * a wildcard descriptor (HD chain) — registered via [`insert_descriptor`], reveals advance
///   the derivation index up to [`BIP32_MAX_INDEX`];
/// * a non-wildcard descriptor (a fixed descriptor with a single derivation) — also registered
///   via [`insert_descriptor`], only ever yields a single spk at index `0`;
/// * a raw script pubkey with no descriptor — registered via [`insert_spk`], also a single spk at
///   index `0`.
///
/// The caller does not need to branch on which kind of keychain a `K` corresponds to: the same
/// [`reveal_next_spk`], [`next_unused_spk`], [`index_of_spk`], etc., calls dispatch internally.
///
/// # Overlap policy
///
/// A single script pubkey may be claimed by exactly one keychain. Inserting a descriptor (or raw
/// spk) whose script would collide with one already tracked by another keychain returns
/// [`InsertError::SpkAlreadyAssigned`]. This keeps the answer to "which keychain owns this spk?"
/// unambiguous; if a script genuinely needs multiple application-level meanings, layer that as
/// application metadata next to the indexer.
///
/// # Lookahead and persistence
///
/// Wildcard descriptors derive `lookahead` additional script pubkeys past the last revealed index,
/// so transactions sending to addresses the user has not yet asked for can still be detected on
/// the next sync. Non-wildcard descriptors and raw spks have no notion of lookahead.
///
/// When `persist_spks` is enabled, derived spks are cached in the [`ChangeSet`] so they can be
/// restored on reload without re-deriving every script from the descriptor.
///
/// [`insert_descriptor`]: Self::insert_descriptor
/// [`insert_spk`]: Self::insert_spk
/// [`reveal_next_spk`]: Self::reveal_next_spk
/// [`next_unused_spk`]: Self::next_unused_spk
/// [`index_of_spk`]: Self::index_of_spk
#[derive(Clone, Debug)]
pub struct TxOutIndex<K> {
    inner: SpkTxOutIndex<(K, u32)>,

    // Descriptor-based keychain state (mirrors `KeychainTxOutIndex`).
    keychain_to_descriptor_id: BTreeMap<K, DescriptorId>,
    descriptor_id_to_keychain: HashMap<DescriptorId, K>,
    descriptors: HashMap<DescriptorId, Descriptor<DescriptorPublicKey>>,
    last_revealed: HashMap<DescriptorId, u32>,

    // Raw-spk keychains: keychains that were registered via `insert_spk` rather than a descriptor.
    raw_keychains: BTreeSet<K>,

    lookahead: u32,

    persist_spks: bool,
    spk_cache: BTreeMap<DescriptorId, HashMap<u32, ScriptBuf>>,
    spk_cache_stage: BTreeMap<DescriptorId, Vec<(u32, ScriptBuf)>>,
}

impl<K> Default for TxOutIndex<K> {
    fn default() -> Self {
        Self::new(DEFAULT_LOOKAHEAD, false)
    }
}

impl<K> AsRef<SpkTxOutIndex<(K, u32)>> for TxOutIndex<K> {
    fn as_ref(&self) -> &SpkTxOutIndex<(K, u32)> {
        &self.inner
    }
}

impl<K: Clone + Ord + Debug> Indexer for TxOutIndex<K> {
    type ChangeSet = ChangeSet;

    fn index_txout(&mut self, outpoint: OutPoint, txout: &TxOut) -> Self::ChangeSet {
        let mut changeset = ChangeSet::default();
        self._index_txout(&mut changeset, outpoint, txout);
        self._empty_stage_into_changeset(&mut changeset);
        changeset
    }

    fn index_tx(&mut self, tx: &bitcoin::Transaction) -> Self::ChangeSet {
        let mut changeset = ChangeSet::default();
        let txid = tx.compute_txid();
        for (vout, txout) in tx.output.iter().enumerate() {
            self._index_txout(&mut changeset, OutPoint::new(txid, vout as u32), txout);
        }
        self._empty_stage_into_changeset(&mut changeset);
        changeset
    }

    fn initial_changeset(&self) -> Self::ChangeSet {
        ChangeSet {
            last_revealed: self.last_revealed.clone().into_iter().collect(),
            spk_cache: self
                .spk_cache
                .iter()
                .map(|(desc, spks)| {
                    (
                        *desc,
                        spks.iter().map(|(i, spk)| (*i, spk.clone())).collect(),
                    )
                })
                .collect(),
        }
    }

    fn apply_changeset(&mut self, changeset: Self::ChangeSet) {
        self.apply_changeset(changeset)
    }

    fn is_tx_relevant(&self, tx: &bitcoin::Transaction) -> bool {
        self.inner.is_relevant(tx)
    }
}

impl<K> TxOutIndex<K> {
    /// Construct a [`TxOutIndex`] with the given `lookahead` and `persist_spks` boolean.
    ///
    /// # Lookahead
    ///
    /// The `lookahead` parameter controls how many script pubkeys to derive *beyond* the highest
    /// revealed index for each wildcard descriptor. With a nonzero `lookahead`, the index can
    /// detect outputs paid to "future" addresses (ahead of what the user has explicitly revealed).
    ///
    /// Non-wildcard descriptors and raw spks ignore `lookahead`.
    ///
    /// # Script pubkey persistence
    ///
    /// If `persist_spks` is `true`, derived spks are recorded in the [`ChangeSet`] so they don't
    /// have to be re-derived from the descriptor on reload. If `false`, derivation happens on
    /// load.
    pub fn new(lookahead: u32, persist_spks: bool) -> Self {
        Self {
            inner: SpkTxOutIndex::default(),
            keychain_to_descriptor_id: Default::default(),
            descriptor_id_to_keychain: Default::default(),
            descriptors: Default::default(),
            last_revealed: Default::default(),
            raw_keychains: Default::default(),
            lookahead,
            persist_spks,
            spk_cache: Default::default(),
            spk_cache_stage: Default::default(),
        }
    }

    /// Get a reference to the internal [`SpkTxOutIndex`].
    pub fn inner(&self) -> &SpkTxOutIndex<(K, u32)> {
        &self.inner
    }

    /// Get the lookahead setting.
    pub fn lookahead(&self) -> u32 {
        self.lookahead
    }
}

impl<K: Clone + Ord + Debug> TxOutIndex<K> {
    /// Construct a `TxOutIndex<K>` from the given `changeset`.
    ///
    /// Shorthand for calling [`new`] and then [`apply_changeset`]. Note that descriptors and raw
    /// spks are not persisted in the changeset — the caller must re-register them via
    /// [`insert_descriptor`] / [`insert_spk`] before any wildcard derivation will produce
    /// meaningful results.
    ///
    /// [`new`]: Self::new
    /// [`apply_changeset`]: Self::apply_changeset
    /// [`insert_descriptor`]: Self::insert_descriptor
    /// [`insert_spk`]: Self::insert_spk
    pub fn from_changeset(lookahead: u32, persist_spks: bool, changeset: ChangeSet) -> Self {
        let mut out = Self::new(lookahead, persist_spks);
        out.apply_changeset(changeset);
        out
    }

    fn _index_txout(&mut self, changeset: &mut ChangeSet, outpoint: OutPoint, txout: &TxOut) {
        if let Some((keychain, index)) = self.inner.scan_txout(outpoint, txout).cloned() {
            // Only descriptor-based keychains can advance their last-revealed cursor and require
            // replenishing the lookahead window. Raw-spk keychains have no derivation, so there's
            // nothing to bump or replenish.
            if let Some(did) = self.keychain_to_descriptor_id.get(&keychain) {
                let did = *did;
                let index_updated = match self.last_revealed.entry(did) {
                    hash_map::Entry::Occupied(mut e) if e.get() < &index => {
                        e.insert(index);
                        true
                    }
                    hash_map::Entry::Vacant(e) => {
                        e.insert(index);
                        true
                    }
                    _ => false,
                };
                if index_updated {
                    changeset.last_revealed.insert(did, index);
                    self.replenish_inner_index(did, &keychain, self.lookahead);
                }
            }
        }
    }

    fn _empty_stage_into_changeset(&mut self, changeset: &mut ChangeSet) {
        if !self.persist_spks {
            return;
        }
        for (did, spks) in core::mem::take(&mut self.spk_cache_stage) {
            debug_assert!(
                {
                    let desc = self.descriptors.get(&did).expect("invariant");
                    spks.iter().all(|(i, spk)| {
                        let exp_spk = desc
                            .at_derivation_index(*i)
                            .expect("must derive")
                            .script_pubkey();
                        &exp_spk == spk
                    })
                },
                "all staged spks must be correct"
            );
            changeset.spk_cache.entry(did).or_default().extend(spks);
        }
    }

    /// Get the set of indexed outpoints, corresponding to tracked keychains.
    pub fn outpoints(&self) -> &BTreeSet<KeychainIndexed<K, OutPoint>> {
        self.inner.outpoints()
    }

    /// Iterate over known txouts that spend to tracked script pubkeys.
    pub fn txouts(
        &self,
    ) -> impl DoubleEndedIterator<Item = KeychainIndexed<K, (OutPoint, &TxOut)>> + ExactSizeIterator
    {
        self.inner
            .txouts()
            .map(|(index, op, txout)| (index.clone(), (op, txout)))
    }

    /// Finds all txouts on a transaction that has previously been scanned and indexed.
    pub fn txouts_in_tx(
        &self,
        txid: Txid,
    ) -> impl DoubleEndedIterator<Item = KeychainIndexed<K, (OutPoint, &TxOut)>> {
        self.inner
            .txouts_in_tx(txid)
            .map(|(index, op, txout)| (index.clone(), (op, txout)))
    }

    /// Return the [`TxOut`] of `outpoint` if it has been indexed, and if it corresponds to a
    /// tracked keychain.
    pub fn txout(&self, outpoint: OutPoint) -> Option<KeychainIndexed<K, &TxOut>> {
        self.inner
            .txout(outpoint)
            .map(|(index, txout)| (index.clone(), txout))
    }

    /// Return the script that exists under the given `keychain`'s `index`.
    pub fn spk_at_index(&self, keychain: K, index: u32) -> Option<ScriptBuf> {
        self.inner.spk_at_index(&(keychain.clone(), index))
    }

    /// Returns the keychain and keychain index associated with the spk.
    pub fn index_of_spk<T>(&self, script: T) -> Option<&(K, u32)>
    where
        T: AsRef<Script>,
    {
        self.inner.index_of_spk(script)
    }

    /// Returns whether the spk under the `keychain`'s `index` has been used.
    pub fn is_used(&self, keychain: K, index: u32) -> bool {
        self.inner.is_used(&(keychain, index))
    }

    /// Marks the script pubkey at `index` as used even though the tracker hasn't seen an output
    /// with it.
    ///
    /// See [`SpkTxOutIndex::mark_used`] for the semantics.
    pub fn mark_used(&mut self, keychain: K, index: u32) -> bool {
        self.inner.mark_used(&(keychain, index))
    }

    /// Undoes the effect of [`mark_used`]. Returns whether the `index` is inserted back into
    /// `unused`.
    ///
    /// [`mark_used`]: Self::mark_used
    pub fn unmark_used(&mut self, keychain: K, index: u32) -> bool {
        self.inner.unmark_used(&(keychain, index))
    }

    /// Compute the total value transfer effect `tx` has on script pubkeys belonging to the
    /// keychains in `range`.
    pub fn sent_and_received(
        &self,
        tx: &Transaction,
        range: impl RangeBounds<K>,
    ) -> (Amount, Amount) {
        self.inner
            .sent_and_received(tx, self.map_to_inner_bounds(range))
    }

    /// Returns the [`SpentTxOut`]s for `tx` relative to script pubkeys belonging to the keychain.
    pub fn spent_txouts<'a>(
        &'a self,
        tx: &'a Transaction,
    ) -> impl Iterator<Item = SpentTxOut<(K, u32)>> + 'a {
        self.inner.spent_txouts(tx)
    }

    /// Returns the [`CreatedTxOut`]s for `tx` relative to the script pubkeys belonging to the
    /// keychain.
    pub fn created_txouts<'a>(
        &'a self,
        tx: &'a Transaction,
    ) -> impl Iterator<Item = CreatedTxOut<(K, u32)>> + 'a {
        self.inner.created_txouts(tx)
    }

    /// Compute the net value that this transaction gives to the script pubkeys in the index.
    pub fn net_value(&self, tx: &Transaction, range: impl RangeBounds<K>) -> SignedAmount {
        self.inner.net_value(tx, self.map_to_inner_bounds(range))
    }
}

impl<K: Clone + Ord + Debug> TxOutIndex<K> {
    /// Return all keychains backed by a descriptor.
    ///
    /// Raw-spk keychains (registered via [`insert_spk`](Self::insert_spk)) are not returned here;
    /// use [`raw_keychains`](Self::raw_keychains) for those.
    pub fn keychains(
        &self,
    ) -> impl DoubleEndedIterator<Item = (K, &Descriptor<DescriptorPublicKey>)> + ExactSizeIterator + '_
    {
        self.keychain_to_descriptor_id
            .iter()
            .map(|(k, did)| (k.clone(), self.descriptors.get(did).expect("invariant")))
    }

    /// Iterate over keychains registered with a raw script pubkey (no descriptor).
    pub fn raw_keychains(&self) -> impl DoubleEndedIterator<Item = &K> + ExactSizeIterator + '_ {
        self.raw_keychains.iter()
    }

    /// Returns `true` if `keychain` is backed by a raw script pubkey rather than a descriptor.
    pub fn is_raw_keychain(&self, keychain: &K) -> bool {
        self.raw_keychains.contains(keychain)
    }

    /// Insert a descriptor with a keychain associated to it.
    ///
    /// Works for wildcard *and* non-wildcard descriptors. For non-wildcard descriptors, the
    /// single derived spk is registered immediately at index `0`.
    ///
    /// The keychain <-> descriptor mapping is one-to-one. Re-inserting the same `(K, descriptor)`
    /// is a no-op and returns `Ok(false)`. Attempting to reassign either side returns an error.
    ///
    /// Returns an error if the descriptor's spk (at any derivation index within the lookahead
    /// window for wildcard descriptors, or at index `0` for non-wildcard ones) overlaps a script
    /// pubkey already tracked by another keychain in this index.
    pub fn insert_descriptor(
        &mut self,
        keychain: K,
        descriptor: Descriptor<DescriptorPublicKey>,
    ) -> Result<bool, InsertError<K>> {
        if self.raw_keychains.contains(&keychain) {
            return Err(InsertError::KeychainAlreadyAssigned {
                keychain,
                existing_assignment: ExistingAssignment::RawSpk,
            });
        }

        let did = descriptor.descriptor_id();
        if !self.keychain_to_descriptor_id.contains_key(&keychain)
            && !self.descriptor_id_to_keychain.contains_key(&did)
        {
            // Check for spk overlap with raw-spk keychains before committing anything to state.
            let probe_index = if descriptor.has_wildcard() {
                self.lookahead.min(BIP32_MAX_INDEX)
            } else {
                0
            };
            for (i, spk) in SpkIterator::new_with_range(&descriptor, 0..=probe_index) {
                if let Some(existing) = self.inner.index_of_spk(&spk) {
                    let existing_keychain = existing.0.clone();
                    // We only need to flag the overlap if it's against a *different* keychain.
                    if existing_keychain != keychain {
                        return Err(InsertError::SpkAlreadyAssigned {
                            spk,
                            attempted_keychain: keychain,
                            existing_keychain,
                            existing_index: existing.1,
                            attempted_index: i,
                        });
                    }
                }
            }

            self.descriptors.insert(did, descriptor.clone());
            self.keychain_to_descriptor_id.insert(keychain.clone(), did);
            self.descriptor_id_to_keychain.insert(did, keychain.clone());
            self.replenish_inner_index(did, &keychain, self.lookahead);
            return Ok(true);
        }

        if let Some(existing_desc_id) = self.keychain_to_descriptor_id.get(&keychain) {
            let descriptor_existing = self.descriptors.get(existing_desc_id).expect("invariant");
            if *existing_desc_id != did {
                return Err(InsertError::KeychainAlreadyAssigned {
                    keychain,
                    existing_assignment: ExistingAssignment::Descriptor(Box::new(
                        descriptor_existing.clone(),
                    )),
                });
            }
        }

        if let Some(existing_keychain) = self.descriptor_id_to_keychain.get(&did) {
            let descriptor_existing = self.descriptors.get(&did).expect("invariant").clone();

            if *existing_keychain != keychain {
                return Err(InsertError::DescriptorAlreadyAssigned {
                    existing_assignment: existing_keychain.clone(),
                    descriptor: Box::new(descriptor_existing),
                });
            }
        }

        Ok(false)
    }

    /// Insert a raw script pubkey under `keychain` (no descriptor).
    ///
    /// Use this for spks the user wants to track directly — for example, a swept output's
    /// scriptPubKey, a counterparty's deposit address, or any script that isn't derived from a
    /// descriptor under the application's control.
    ///
    /// Each raw-spk keychain holds exactly one script pubkey, conventionally at index `0`. Calls
    /// such as [`reveal_next_spk`](Self::reveal_next_spk) and
    /// [`next_unused_spk`](Self::next_unused_spk) yield that single spk and never advance past it.
    ///
    /// Re-inserting the same `(K, spk)` is a no-op and returns `Ok(false)`. Attempting to reassign
    /// the keychain to a different spk — or to a descriptor — returns an error, as does inserting
    /// a script that's already tracked by another keychain.
    pub fn insert_spk(&mut self, keychain: K, spk: ScriptBuf) -> Result<bool, InsertError<K>> {
        if self.keychain_to_descriptor_id.contains_key(&keychain) {
            let did = self
                .keychain_to_descriptor_id
                .get(&keychain)
                .expect("just checked");
            let existing_desc = self.descriptors.get(did).expect("invariant").clone();
            return Err(InsertError::KeychainAlreadyAssigned {
                keychain,
                existing_assignment: ExistingAssignment::Descriptor(Box::new(existing_desc)),
            });
        }

        if let Some(existing) = self.inner.index_of_spk(&spk) {
            let existing_keychain = existing.0.clone();
            let existing_index = existing.1;
            if existing_keychain == keychain && existing_index == 0 {
                // Same (keychain, spk) already registered — no-op.
                return Ok(false);
            }
            return Err(InsertError::SpkAlreadyAssigned {
                spk,
                attempted_keychain: keychain,
                existing_keychain,
                existing_index,
                attempted_index: 0,
            });
        }

        if self.raw_keychains.contains(&keychain) {
            // Keychain is registered as raw, but the existing spk is different.
            return Err(InsertError::KeychainAlreadyAssigned {
                keychain,
                existing_assignment: ExistingAssignment::RawSpk,
            });
        }

        let inserted = self.inner.insert_spk((keychain.clone(), 0), spk);
        debug_assert!(inserted, "spk overlap should have been caught above");
        self.raw_keychains.insert(keychain);
        Ok(true)
    }

    /// Gets the descriptor associated with the keychain, if any.
    ///
    /// Returns `None` for raw-spk keychains or unknown keychains.
    pub fn get_descriptor(&self, keychain: K) -> Option<&Descriptor<DescriptorPublicKey>> {
        let did = self.keychain_to_descriptor_id.get(&keychain)?;
        self.descriptors.get(did)
    }

    /// Store lookahead scripts until `target_index` (inclusive).
    ///
    /// This does not change the global `lookahead` setting. No-op for raw-spk keychains.
    pub fn lookahead_to_target(&mut self, keychain: K, target_index: u32) -> ChangeSet {
        let mut changeset = ChangeSet::default();
        if let Some((next_index, _)) = self.next_index(keychain.clone()) {
            let temp_lookahead = (target_index + 1)
                .checked_sub(next_index)
                .filter(|&index| index > 0);

            if let Some(temp_lookahead) = temp_lookahead {
                self.replenish_inner_index_keychain(keychain, temp_lookahead);
            }
        }
        self._empty_stage_into_changeset(&mut changeset);
        changeset
    }

    fn replenish_inner_index_did(&mut self, did: DescriptorId, lookahead: u32) {
        if let Some(keychain) = self.descriptor_id_to_keychain.get(&did).cloned() {
            self.replenish_inner_index(did, &keychain, lookahead);
        }
    }

    fn replenish_inner_index_keychain(&mut self, keychain: K, lookahead: u32) {
        if let Some(did) = self.keychain_to_descriptor_id.get(&keychain) {
            self.replenish_inner_index(*did, &keychain, lookahead);
        }
    }

    fn replenish_inner_index(&mut self, did: DescriptorId, keychain: &K, lookahead: u32) {
        let descriptor = self.descriptors.get(&did).expect("invariant");

        let mut next_index = self
            .inner
            .all_spks()
            .range(&(keychain.clone(), u32::MIN)..=&(keychain.clone(), u32::MAX))
            .last()
            .map_or(0, |((_, index), _)| *index + 1);

        let stop_index = if descriptor.has_wildcard() {
            let next_reveal_index = self.last_revealed.get(&did).map_or(0, |v| *v + 1);
            (next_reveal_index + lookahead).min(BIP32_MAX_INDEX)
        } else {
            1
        };

        if self.persist_spks {
            let derive_spk = {
                let secp = Secp256k1::verification_only();
                let _desc = &descriptor;
                move |spk_i: u32| -> ScriptBuf {
                    _desc
                        .derived_descriptor(&secp, spk_i)
                        .expect("The descriptor cannot have hardened derivation")
                        .script_pubkey()
                }
            };
            let cached_spk_iter = core::iter::from_fn({
                let spk_cache = self.spk_cache.entry(did).or_default();
                let spk_stage = self.spk_cache_stage.entry(did).or_default();
                let _i = &mut next_index;
                move || -> Option<Indexed<ScriptBuf>> {
                    if *_i >= stop_index {
                        return None;
                    }
                    let spk_i = *_i;
                    *_i = spk_i.saturating_add(1);

                    if let Some(spk) = spk_cache.get(&spk_i) {
                        debug_assert_eq!(spk, &derive_spk(spk_i), "cached spk must equal derived");
                        return Some((spk_i, spk.clone()));
                    }
                    let spk = derive_spk(spk_i);
                    spk_stage.push((spk_i, spk.clone()));
                    spk_cache.insert(spk_i, spk.clone());
                    Some((spk_i, spk))
                }
            });
            for (new_index, new_spk) in cached_spk_iter {
                let _inserted = self
                    .inner
                    .insert_spk((keychain.clone(), new_index), new_spk);
                debug_assert!(_inserted, "replenish lookahead: must not have existing spk: keychain={keychain:?}, lookahead={lookahead}, next_index={next_index}");
            }
        } else {
            let spk_iter = SpkIterator::new_with_range(descriptor, next_index..stop_index);
            for (new_index, new_spk) in spk_iter {
                let _inserted = self
                    .inner
                    .insert_spk((keychain.clone(), new_index), new_spk);
                debug_assert!(_inserted, "replenish lookahead: must not have existing spk: keychain={keychain:?}, lookahead={lookahead}, next_index={next_index}");
            }
        }
    }

    /// Get an unbounded spk iterator over a wildcard `keychain`. Returns `None` if the keychain
    /// is unknown or is a raw-spk keychain.
    pub fn unbounded_spk_iter(
        &self,
        keychain: K,
    ) -> Option<SpkIterator<Descriptor<DescriptorPublicKey>>> {
        let descriptor = self.get_descriptor(keychain)?.clone();
        Some(SpkIterator::new(descriptor))
    }

    /// Get unbounded spk iterators for all descriptor-backed keychains.
    pub fn all_unbounded_spk_iters(
        &self,
    ) -> BTreeMap<K, SpkIterator<Descriptor<DescriptorPublicKey>>> {
        self.keychain_to_descriptor_id
            .iter()
            .map(|(k, did)| {
                (
                    k.clone(),
                    SpkIterator::new(self.descriptors.get(did).expect("invariant").clone()),
                )
            })
            .collect()
    }

    /// Iterate over revealed spks of keychains in `range`.
    ///
    /// Includes raw-spk keychains (they're always considered revealed).
    pub fn revealed_spks(
        &self,
        range: impl RangeBounds<K>,
    ) -> impl Iterator<Item = KeychainIndexed<K, ScriptBuf>> + '_ {
        let start = range.start_bound();
        let end = range.end_bound();
        let mut iter_last_revealed = self
            .keychain_to_descriptor_id
            .range((start, end))
            .map(|(k, did)| (k, self.last_revealed.get(did).cloned()));
        let mut iter_spks = self
            .inner
            .all_spks()
            .range(self.map_to_inner_bounds((start, end)));
        let mut current_keychain = iter_last_revealed.next();
        let raw_keychains = &self.raw_keychains;
        core::iter::from_fn(move || loop {
            let ((keychain, index), spk) = iter_spks.next()?;

            // Raw-spk keychains are always considered revealed.
            if raw_keychains.contains(keychain) {
                return Some(((keychain.clone(), *index), spk.clone()));
            }

            // For descriptor-backed keychains we need to filter against the keychain's
            // `last_revealed` cursor — lookahead-cached spks above that cursor have not been
            // revealed.
            while current_keychain.is_some_and(|(k, _)| k < keychain) {
                current_keychain = iter_last_revealed.next();
            }
            let (current_keychain_k, last_revealed) = current_keychain?;

            if current_keychain_k == keychain && Some(*index) <= last_revealed {
                return Some(((keychain.clone(), *index), spk.clone()));
            }
        })
    }

    /// Iterate over revealed spks of the given `keychain` with ascending indices.
    ///
    /// For raw-spk keychains, yields the single registered spk at index 0.
    pub fn revealed_keychain_spks(
        &self,
        keychain: K,
    ) -> impl DoubleEndedIterator<Item = Indexed<ScriptBuf>> + '_ {
        let end = if self.raw_keychains.contains(&keychain) {
            1
        } else {
            self.last_revealed_index(keychain.clone())
                .map(|v| v + 1)
                .unwrap_or(0)
        };
        self.inner
            .all_spks()
            .range((keychain.clone(), 0)..(keychain.clone(), end))
            .map(|((_, index), spk)| (*index, spk.clone()))
    }

    /// Iterate over revealed, but unused, spks of all keychains.
    pub fn unused_spks(
        &self,
    ) -> impl DoubleEndedIterator<Item = KeychainIndexed<K, ScriptBuf>> + Clone + '_ {
        // Descriptor-based keychains: walk `last_revealed`-bounded ranges.
        let descriptor_spks = self.keychain_to_descriptor_id.keys().flat_map(|keychain| {
            self.unused_keychain_spks(keychain.clone())
                .map(|(i, spk)| ((keychain.clone(), i), spk.clone()))
        });
        let raw_spks = self.raw_keychains.iter().flat_map(|keychain| {
            self.unused_keychain_spks(keychain.clone())
                .map(|(i, spk)| ((keychain.clone(), i), spk.clone()))
        });
        descriptor_spks.chain(raw_spks)
    }

    /// Iterate over revealed, but unused, spks of the given `keychain`.
    pub fn unused_keychain_spks(
        &self,
        keychain: K,
    ) -> impl DoubleEndedIterator<Item = Indexed<ScriptBuf>> + Clone + '_ {
        let end = if self.raw_keychains.contains(&keychain) {
            1
        } else {
            match self.keychain_to_descriptor_id.get(&keychain) {
                Some(did) => self.last_revealed.get(did).map(|v| *v + 1).unwrap_or(0),
                None => 0,
            }
        };

        self.inner
            .unused_spks((keychain.clone(), 0)..(keychain.clone(), end))
            .map(|((_, i), spk)| (*i, spk))
    }

    /// Get the next derivation index for `keychain`.
    ///
    /// The second tuple field is `true` if the index has not been revealed before, `false` if
    /// it has (i.e. for non-wildcard descriptors and raw spks after their first reveal, or for
    /// wildcard descriptors that hit `BIP32_MAX_INDEX`).
    ///
    /// Returns `None` for unknown keychains.
    pub fn next_index(&self, keychain: K) -> Option<(u32, bool)> {
        if self.raw_keychains.contains(&keychain) {
            // Raw spks behave like non-wildcard descriptors: there's always exactly one spk at
            // index 0, which is "revealed" as soon as it's inserted.
            return Some((0, false));
        }

        let did = self.keychain_to_descriptor_id.get(&keychain)?;
        let last_index = self.last_revealed.get(did).cloned();
        let descriptor = self.descriptors.get(did).expect("invariant");

        let has_wildcard = descriptor.has_wildcard();

        Some(match last_index {
            None => (0, true),
            Some(_) if !has_wildcard => (0, false),
            Some(index) if index > BIP32_MAX_INDEX => {
                unreachable!("index is out of bounds")
            }
            Some(index) if index == BIP32_MAX_INDEX => (index, false),
            Some(index) => (index + 1, true),
        })
    }

    /// Get the last derivation index that is revealed for each descriptor-backed keychain.
    pub fn last_revealed_indices(&self) -> BTreeMap<K, u32> {
        self.last_revealed
            .iter()
            .filter_map(|(desc_id, index)| {
                let keychain = self.descriptor_id_to_keychain.get(desc_id)?;
                Some((keychain.clone(), *index))
            })
            .collect()
    }

    /// Get the last derivation index revealed for `keychain`.
    ///
    /// For raw-spk keychains, returns `Some(0)` after [`insert_spk`](Self::insert_spk).
    pub fn last_revealed_index(&self, keychain: K) -> Option<u32> {
        if self.raw_keychains.contains(&keychain) {
            return Some(0);
        }
        let descriptor_id = self.keychain_to_descriptor_id.get(&keychain)?;
        self.last_revealed.get(descriptor_id).cloned()
    }

    /// Convenience method to call [`Self::reveal_to_target`] on multiple keychains.
    pub fn reveal_to_target_multi(&mut self, keychains: &BTreeMap<K, u32>) -> ChangeSet {
        let mut changeset = ChangeSet::default();

        for (keychain, &index) in keychains {
            self._reveal_to_target(&mut changeset, keychain.clone(), index);
        }

        self._empty_stage_into_changeset(&mut changeset);
        changeset
    }

    /// Reveals script pubkeys of the `keychain`'s descriptor **up to and including** the
    /// `target_index`.
    ///
    /// For non-wildcard descriptors and raw spks, this is best-effort and will reveal the single
    /// available spk if not already revealed.
    ///
    /// Returns `None` if the provided `keychain` doesn't exist.
    #[must_use]
    pub fn reveal_to_target(
        &mut self,
        keychain: K,
        target_index: u32,
    ) -> Option<(Vec<Indexed<ScriptBuf>>, ChangeSet)> {
        let mut changeset = ChangeSet::default();
        let revealed_spks = self._reveal_to_target(&mut changeset, keychain, target_index)?;
        self._empty_stage_into_changeset(&mut changeset);
        Some((revealed_spks, changeset))
    }

    fn _reveal_to_target(
        &mut self,
        changeset: &mut ChangeSet,
        keychain: K,
        target_index: u32,
    ) -> Option<Vec<Indexed<ScriptBuf>>> {
        let mut spks: Vec<Indexed<ScriptBuf>> = vec![];
        loop {
            let (i, new) = self.next_index(keychain.clone())?;
            if !new || i > target_index {
                break;
            }
            match self._reveal_next_spk(changeset, keychain.clone()) {
                Some(indexed_spk) => spks.push(indexed_spk),
                None => break,
            }
        }
        Some(spks)
    }

    /// Attempts to reveal the next script pubkey for `keychain`.
    ///
    /// For raw-spk keychains, always returns the single registered `(0, spk)` with an empty
    /// changeset.
    ///
    /// Returns `None` if the provided keychain doesn't exist.
    pub fn reveal_next_spk(&mut self, keychain: K) -> Option<(Indexed<ScriptBuf>, ChangeSet)> {
        let mut changeset = ChangeSet::default();
        let indexed_spk = self._reveal_next_spk(&mut changeset, keychain)?;
        self._empty_stage_into_changeset(&mut changeset);
        Some((indexed_spk, changeset))
    }

    fn _reveal_next_spk(
        &mut self,
        changeset: &mut ChangeSet,
        keychain: K,
    ) -> Option<Indexed<ScriptBuf>> {
        if self.raw_keychains.contains(&keychain) {
            let spk = self.inner.spk_at_index(&(keychain, 0)).expect("invariant");
            return Some((0, spk));
        }

        let (next_index, new) = self.next_index(keychain.clone())?;
        if new {
            let did = self.keychain_to_descriptor_id.get(&keychain)?;
            self.last_revealed.insert(*did, next_index);
            changeset.last_revealed.insert(*did, next_index);
            self.replenish_inner_index(*did, &keychain, self.lookahead);
        }
        let script = self
            .inner
            .spk_at_index(&(keychain.clone(), next_index))
            .expect("we just inserted it");
        Some((next_index, script))
    }

    /// Gets the next unused script pubkey in the keychain.
    ///
    /// For raw-spk keychains: returns the registered spk if unused, otherwise `None`.
    pub fn next_unused_spk(&mut self, keychain: K) -> Option<(Indexed<ScriptBuf>, ChangeSet)> {
        let mut changeset = ChangeSet::default();
        let next_unused = self
            .unused_keychain_spks(keychain.clone())
            .next()
            .map(|(i, spk)| (i, spk.to_owned()));
        let spk = next_unused.or_else(|| self._reveal_next_spk(&mut changeset, keychain))?;
        self._empty_stage_into_changeset(&mut changeset);
        Some((spk, changeset))
    }

    /// Iterate over all [`OutPoint`]s that have `TxOut`s with script pubkeys belonging to
    /// `keychain`.
    pub fn keychain_outpoints(
        &self,
        keychain: K,
    ) -> impl DoubleEndedIterator<Item = Indexed<OutPoint>> + '_ {
        self.keychain_outpoints_in_range(keychain.clone()..=keychain)
            .map(|((_, i), op)| (i, op))
    }

    /// Iterate over [`OutPoint`]s belonging to keychains in `range`.
    pub fn keychain_outpoints_in_range<'a>(
        &'a self,
        range: impl RangeBounds<K> + 'a,
    ) -> impl DoubleEndedIterator<Item = KeychainIndexed<K, OutPoint>> + 'a {
        self.inner
            .outputs_in_range(self.map_to_inner_bounds(range))
            .map(|((k, i), op)| ((k.clone(), *i), op))
    }

    fn map_to_inner_bounds(&self, bound: impl RangeBounds<K>) -> impl RangeBounds<(K, u32)> {
        let start = match bound.start_bound() {
            Bound::Included(keychain) => Bound::Included((keychain.clone(), u32::MIN)),
            Bound::Excluded(keychain) => Bound::Excluded((keychain.clone(), u32::MAX)),
            Bound::Unbounded => Bound::Unbounded,
        };
        let end = match bound.end_bound() {
            Bound::Included(keychain) => Bound::Included((keychain.clone(), u32::MAX)),
            Bound::Excluded(keychain) => Bound::Excluded((keychain.clone(), u32::MIN)),
            Bound::Unbounded => Bound::Unbounded,
        };

        (start, end)
    }

    /// Returns the highest derivation index of the `keychain` where this index has found a
    /// [`TxOut`] with its script pubkey.
    pub fn last_used_index(&self, keychain: K) -> Option<u32> {
        self.keychain_outpoints(keychain).last().map(|(i, _)| i)
    }

    /// Returns the highest derivation index of each keychain that has been found with a [`TxOut`]
    /// matching the indexer.
    pub fn last_used_indices(&self) -> BTreeMap<K, u32> {
        let descriptor_iter = self.keychain_to_descriptor_id.keys();
        let raw_iter = self.raw_keychains.iter();
        descriptor_iter
            .chain(raw_iter)
            .filter_map(|keychain| {
                self.last_used_index(keychain.clone())
                    .map(|index| (keychain.clone(), index))
            })
            .collect()
    }

    /// Applies the [`ChangeSet`] to the [`TxOutIndex`].
    pub fn apply_changeset(&mut self, changeset: ChangeSet) {
        if self.persist_spks {
            for (did, spks) in changeset.spk_cache {
                self.spk_cache.entry(did).or_default().extend(spks);
            }
        }
        for (did, index) in changeset.last_revealed {
            let v = self.last_revealed.entry(did).or_default();
            *v = index.max(*v);
            self.replenish_inner_index_did(did, self.lookahead);
        }
    }
}

/// Error returned from [`TxOutIndex::insert_descriptor`] and [`TxOutIndex::insert_spk`].
#[derive(Clone, Debug, PartialEq)]
pub enum InsertError<K> {
    /// The descriptor has already been assigned to another keychain.
    DescriptorAlreadyAssigned {
        /// The descriptor that was attempted.
        descriptor: Box<Descriptor<DescriptorPublicKey>>,
        /// The keychain that already owns this descriptor.
        existing_assignment: K,
    },
    /// The keychain is already assigned to a different descriptor or raw spk.
    KeychainAlreadyAssigned {
        /// The keychain that was attempted.
        keychain: K,
        /// What the keychain is already assigned to.
        existing_assignment: ExistingAssignment,
    },
    /// The script pubkey is already tracked by a different keychain.
    SpkAlreadyAssigned {
        /// The conflicting script pubkey.
        spk: ScriptBuf,
        /// The keychain we tried to register the spk under.
        attempted_keychain: K,
        /// The derivation index we tried to register the spk at.
        attempted_index: u32,
        /// The keychain that already owns this spk.
        existing_keychain: K,
        /// The derivation index the spk is owned at.
        existing_index: u32,
    },
}

/// Describes what a keychain is already assigned to.
#[derive(Clone, Debug, PartialEq)]
pub enum ExistingAssignment {
    /// The keychain is already assigned to a descriptor.
    Descriptor(Box<Descriptor<DescriptorPublicKey>>),
    /// The keychain is already assigned to a raw script pubkey via
    /// [`TxOutIndex::insert_spk`](TxOutIndex::insert_spk).
    RawSpk,
}

impl core::fmt::Display for ExistingAssignment {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            ExistingAssignment::Descriptor(desc) => write!(f, "descriptor '{desc}'"),
            ExistingAssignment::RawSpk => write!(f, "a raw script pubkey"),
        }
    }
}

impl<K: core::fmt::Display> core::fmt::Display for InsertError<K> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            InsertError::DescriptorAlreadyAssigned {
                existing_assignment,
                descriptor,
            } => {
                write!(
                    f,
                    "descriptor '{descriptor}' is already assigned to keychain '{existing_assignment}'"
                )
            }
            InsertError::KeychainAlreadyAssigned {
                existing_assignment,
                keychain,
            } => {
                write!(
                    f,
                    "keychain '{keychain}' is already assigned to {existing_assignment}"
                )
            }
            InsertError::SpkAlreadyAssigned {
                spk,
                attempted_keychain,
                attempted_index,
                existing_keychain,
                existing_index,
            } => {
                write!(
                    f,
                    "script pubkey '{spk}' attempted at ('{attempted_keychain}', {attempted_index}) is already assigned to ('{existing_keychain}', {existing_index})"
                )
            }
        }
    }
}

impl<K: core::fmt::Display + core::fmt::Debug> core::error::Error for InsertError<K> {}

/// Trait to extend [`SyncRequestBuilder`].
pub trait SyncRequestBuilderExt<K> {
    /// Add [`Script`]s that are revealed by the `indexer` for the given `spk_range`.
    fn revealed_spks_from_txout_index<R>(self, indexer: &TxOutIndex<K>, spk_range: R) -> Self
    where
        R: core::ops::RangeBounds<K>;

    /// Add [`Script`]s that are revealed by the `indexer` but currently unused.
    fn unused_spks_from_txout_index(self, indexer: &TxOutIndex<K>) -> Self;
}

impl<K: Clone + Ord + core::fmt::Debug> SyncRequestBuilderExt<K> for SyncRequestBuilder<(K, u32)> {
    fn revealed_spks_from_txout_index<R>(self, indexer: &TxOutIndex<K>, spk_range: R) -> Self
    where
        R: core::ops::RangeBounds<K>,
    {
        self.spks_with_indexes(indexer.revealed_spks(spk_range))
    }

    fn unused_spks_from_txout_index(self, indexer: &TxOutIndex<K>) -> Self {
        self.spks_with_indexes(indexer.unused_spks())
    }
}

/// Trait to extend [`FullScanRequestBuilder`].
pub trait FullScanRequestBuilderExt<K> {
    /// Add spk iterators for each descriptor-backed keychain tracked in `indexer`.
    fn spks_from_txout_index(self, indexer: &TxOutIndex<K>) -> Self;
}

impl<K: Clone + Ord + core::fmt::Debug> FullScanRequestBuilderExt<K> for FullScanRequestBuilder<K> {
    fn spks_from_txout_index(mut self, indexer: &TxOutIndex<K>) -> Self {
        for (keychain, spks) in indexer.all_unbounded_spk_iters() {
            let last_revealed = indexer.last_revealed_index(keychain.clone());
            self = self.spks_for_keychain(keychain.clone(), spks);
            if let Some(index) = last_revealed {
                self = self.last_revealed_for_keychain(keychain, index);
            }
        }
        self
    }
}
